name: Build

on:
  push:
    branches:
      - 'master'

jobs:

  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: 🧪 Run Tests
        run: ./gradlew shared:allTests --stacktrace